### ISSUE TITLE
Doesn't Clear table on empty results

### ISSUE THREAD

**Issue by FabianInostroza** [sqlitebrowser/sqlitebrowser#1034]
### Details for the issue

Running a query that returns some data and then running another query that returns no data doesn't update (clear) the table shown on the "Execute SQL" tab.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro: Debian Stretch)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [x] Other: 3.9.9 (uncompressed deb from ubuntu ppa)

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Have you tried the latest package from here:
https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser-testing

This doesn't occur on the Windows flavour, so just ensuring you've the latest version.

**Comment by justinclift** [comment]
From memory, we fixed this a while after the 3.9.1.  So the "sqlitebrowser-testing" PPA which @chrisjlocke is pointing to shouldn't have this problem. :smile:

**Comment by FabianInostroza** [comment]
I think that the 3.9.9 version I tested was downloaded from that site.
Downloaded it again to be sure and the problem is still there. The problem is still there but it only 
occurs if the query contains comments before the sentence with empty results.

Note that when there are no comments before the sentence the status control shows "<n> rows returned in <x> ms...."
and when there are comments before the sentence it shows "Query executed successfully:..."

**Comment by mgrojo** [comment]
@FabianInostroza Does it still happens with a newer version? I am unable to reproduce it.

**Comment by FabianInostroza** [comment]
@mgrojo It works fine now. I will close the issue.

**Comment by justinclift** [comment]
Awesome.  Thanks for checking @FabianInostroza. :smile:
