### ISSUE TITLE
Problems with WITHOUT ROWID tables

### ISSUE THREAD

**Issue by mikf** [sqlitebrowser/sqlitebrowser#1332]
### Details for the issue

Interacting with a `WITHOUT ROWID` table causes multiple issues:

```SQL
CREATE TABLE test (item PRIMARY KEY, extra) WITHOUT ROWID;
INSERT INTO test VALUES("test1", 123);
INSERT INTO test VALUES("'test2': 'value'", 234);
```

1. Trying to delete the second row in DB4S by selecting it and clicking "Delete Record"  fails with

```
executeSQL:  "DELETE FROM `test` WHERE `item` IN (''test2': 'value'');" -> near "test2": syntax error
deleteRecord:  "near \"test2\": syntax error (DELETE FROM `test` WHERE `item` IN (''test2': 'value'');)"
```

Probably because of the single quote characters.

This row vanishes in the "Browse Data" view, even though it wasn't actually deleted, and re-appears whenever this view gets refreshed.

2. The `PRIMARY KEY` column is displayed twice:

![sqlitebrowser](https://user-images.githubusercontent.com/5375314/36791166-51d2ea76-1c97-11e8-9c41-3930c810d67b.jpg)

Right-clicking on the column headers and selecting and unselecting "Show rowid column" removes the first `item` column, until the "Browse Data" view gets refreshed. Afterwards the "Filter" entries in the first row are misaligned.

![sqlitebrowser2](https://user-images.githubusercontent.com/5375314/36791526-69bd67be-1c98-11e8-850d-a77b4bd7102d.jpg)

After view refresh:
![sqlitebrowser3](https://user-images.githubusercontent.com/5375314/36791540-706c710e-1c98-11e8-982a-bed9e960684d.jpg)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks for the bug report @mikf.  Which Linux distro are you using?

Asking because we've fixed some bugs with the rowid bits since the last release.  If you're using Ubuntu it's probably worth trying the nightly builds (info on the front page).  If you're using a different distro though, you'd probably need to compile things yourself (not hard). :smile:

**Comment by mikf** [comment]
So, I cloned this repo and compiled the latest version.
The display errors mention in the second point are all gone, but everything in the first one is still happening: Same error message and the row still disappears temporarily.

**Comment by justinclift** [comment]
Arggh.  Bug is still present then.  Damn. :wink:

**Comment by mikf** [comment]
DB4S tries to execute ```DELETE FROM `test` WHERE `item` IN (''test2': 'value'');```, which also fails in the command-line tool.
```
sqlite> DELETE FROM `test` WHERE `item` IN (''test2': 'value'');
Error: near "test2": syntax error
sqlite>
```

But this query works if you double each single `'`:
```
sqlite> DELETE FROM `test` WHERE `item` IN ('''test2'': ''value''');
sqlite>
```

The documentation also mentions to encode single quotations marks by putting two of them in a row:

> A string constant is formed by enclosing the string in single quotes ('). A single quote within the string can be encoded by putting two single quotes in a row - as in Pascal. C-style escapes using the backslash character are not supported because they are not standard SQL.

So maybe replacing `'` with `''` is all there is to it?

**Comment by justinclift** [comment]
Yep, hopefully it's that simple. :smile:

**Comment by mgrojo** [comment]
@mikf I think both problems are now solved. 1. is fixed by properly doubling the single quote when needed and 2. by detecting WITHOUT ROWID tables and not showing the "Show rowid column" for them, since it doesn't make sense and breaks several functions.

However there is a background issue, now hidden in this particular case, but still possible:

> This row vanishes in the "Browse Data" view, even though it wasn't actually deleted, and re-appears whenever this view gets refreshed.

That needs more thought.

Might you gather some time for testing with the next nightly build? The fix will be available tomorrow in https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment]
@mikf is using Linux, so doesn't need to wait for a nightly build. :wink:

**Comment by mikf** [comment]
I tested the changes in your last commit.
Deleting and updating rows with a `'` in their "rowid" works and "Show rowid column" is no longer displayed, but I found some other, possibly related, issues:

- The "rowid" column still gets shown whenever you either apply a filter or click the column header.
- Updating the `PRIMARY KEY` column of a row doesn't properly update its associated `rowid` (at least that's my guess at to what is happening), which prevents any further updates in said row.
  The UI allows and shows changes made to such a row, but refreshing the view reverts everything back to the state just after the first update to the `PRIMARY KEY` column.
-  Records created by the "New Record" button can't be updated or deleted at all, even after refreshing.
  As before, changing values or deleting such a row is shown in the UI, but nothing actually happens in the underlying database.

**Comment by mgrojo** [comment]
@mikf I finally had some time to look at this and I think I've found a solution. I've committed it to a branch (string_pk_without_rowid) and made a pull request (#1559), because we want to make a release soon and I don't want to commit to master any code that might break other parts. But given that you can compile from the source, could you fetch the branch and give it a try for confirming whether it's fixed for you?

**Comment by mikf** [comment]
Had some trouble building your branch (same problems as #1439), but I eventually got it working with `qmake + make` (instead of `cmake + make`).

Your solution appear to have fixed all the issues mentioned above. I've been playing around with the test database from above and creating, modifying and deleting records in any order works as it should.

**Comment by mgrojo** [comment]
Thanks for the information. I hope the fix can get to the release. It's good that you've confirmed that it's working for you.

**Comment by justinclift** [comment]
@mgrojo I haven't yet created the branch in git for 3.11 (am still getting a new Win dev environment set up, as I need to update our SQLcipher pieces anyway), so there's still time to add things in if you reckon they're important. :smile:

**Comment by mgrojo** [comment]
@justinclift I'd like the PR reviewed by @MKleusberg. Although it's simple, I don't want to introduce some unexpected behaviour so close to the release version.

**Comment by justinclift** [comment]
No worries at all. :smile:

**Comment by MKleusberg** [comment]
I think this is solved. Is the 3.11.2 release working for you, @mikf? :smile:

**Comment by mikf** [comment]
3.11.2 is working without any issues. Thank you all for fixing this.

**Comment by justinclift** [comment]
Awesome, thanks for confirming @mikf. :smile:
