### ISSUE TITLE
Crash with discarding changes

### ISSUE THREAD

**Issue by jungle-boogie** [sqlitebrowser/sqlitebrowser#1484]
Details for the issue
--------------------

#### What did you do?
Opened an existing database
Insert new record via GUI
Update record with data via GUI
Close database via red X
Say NO to save changes question
Notice crash

#### What did you expect to see?
Database closes and sqlitebrowser not crash

#### What did you see instead?
Crashing sqlitebrowser

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x ] Windows: ( version: 8.1 )

#### What is your DB4S version?

- [x ] Other:  23 july nightly build

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @jungle-boogie.  That's definitely not good. :smile:

**Comment by karim** [comment]
I think this one is related to scrolling, and not inserting data. The crash exists in the latest nightly version.  To reproduce..

1. Open any database
2. Scroll down a little
3. Close the app by pressing the red [X] button
4. Instant crash

It is strange cause if you scrolled down then scrolled back up to the top and closed the app, it doesn't crash. It seems like it is crashing if you closed the app while the first row is not visible in the view.

The last working version without this crash is the one built on 8th June. @jungle-boogie Can you try this version and see if it is working for you?

**Comment by jungle-boogie** [comment]
Hi Karim,

1. Where would I get a build from the 8th of June?

2. In a test database I had, I didn't have much data where I needed to
scroll, at least I didn't think I did. Or do you mean simlp moving the
mouse?
I did notice that if I inserted a record, kept the data, saved, then
closed, all was good.

**Comment by karim** [comment]
> 1. Where would I get a build from the 8th of June?

For 64-bit builds https://nightlies.sqlitebrowser.org/win64/

> 2. In a test database I had, I didn't have much data where I needed to scroll, at least I didn't think I did. Or do you mean simlp moving the mouse?

It is the same using the mouse or clicking the scrollbar. I noticed if the first row in the database is hidden and I closed the app it crashes. It happens without inserting data too.

**Comment by mgrojo** [comment]
I think I've fixed this crash. It was indeed the same problem than issue #1480.  @jungle-boogie Could you please confirm that it's fixed for you with tomorrow's nightly build?

**Comment by karim** [comment]
@mgrojo Still crashing for me using the latest nightly (28th July). 8th June and earlier builds are fine.

**Comment by mgrojo** [comment]
@karim Is your nightly the one currently stored in https://nightlies.sqlitebrowser.org/latest/ with date '29-Jul-2018 04:03' (For me. No time zone displayed)? The commit was on '28-Jul-2018 14:34 CEST', so that one from 29-July should have the correction (I cannot test it now on Windows), but the previous one would be earlier than the commit. I guess you might have used that.

**Comment by karim** [comment]
@mgrojo Thank you very much. It worked. :smiley: 

You are correct, the one I used (28th July) was built without your commit. It was the latest one when I checked, and now I see the 29th July build which fixed the problem. Thanks again.

**Comment by jungle-boogie** [comment]
Yes! Looks like @mgrojo's fix worked! The application is no longer crashing.

Thanks for the quick fix.
