### ISSUE TITLE
Mac version references incorrect shortcut

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [sqlitebrowser/sqlitebrowser#1539]
Details for the issue
--------------------
<img width="339" alt="screen shot 2018-09-23 at 5 35 01 pm" src="https://user-images.githubusercontent.com/23037821/45934734-0747b500-bf57-11e8-8af0-ded5ff5222ae.png">
In Mac, it's Command + shift + click

#### What did you expect to see?

Command + shift + click
#### What did you see instead?
Ctrl + shift + click

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version: 12.0 )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds 
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh.  I know we've made some changes to the displayed shortcuts since the last release (3.10.1), but I'm not sure if they're for OSX or not.

Ironically... I don't have handy access to an OSX box atm, so can't really test the nightly build myself either.  Um... if you do have a few minutes to check after all, it would be useful. :innocent:

**Comment by ThinkDigitalRepair** [comment]
OK, just for you 😄

**Comment by ThinkDigitalRepair** [comment]
Yes, it still shows the same incorrect shortcut in v3.10.99

**Comment by justinclift** [comment]
Thanks @ThinkDigitalRepair, we'll need to get that fixed then. :smile:

**Comment by mgrojo** [comment]
I cannot test it under Mac, but according to Qt documentation, this particular case should be fixed now.

But there are other cases of key sequences referenced in tooltips or What's This info that cannot be fixed so easily. They are in *.ui files. If somebody knows have to fix these, please share here the tip:

```
EditDialog.ui:289:        <string>Apply data to cell [Ctrl+Return]</string>
MainWindow.ui:138:             <string>Refresh the data in the selected table [F5, Ctrl+R]</string>
MainWindow.ui:237: - Ctrl+&quot; for duplicating the current record.
MainWindow.ui:238: - Ctrl+' for copying the value from the cell above.
MainWindow.ui:1681:    <string>Execute all/selected SQL [F5, Ctrl+Return, Ctrl+R]</string>
MainWindow.ui:2063:    <string>Find text in SQL editor [Ctrl+F]</string>
MainWindow.ui:2084:    <string>Find or replace text in SQL editor [Ctrl+H]</string>
MainWindow.ui:2306:    <string>Print text from current SQL editor tab [Ctrl+P]</string>
PlotDock.ui:75:Click on points to select them in the plot and in the table. Ctrl+Click for selecting a range of points.

```

**Comment by ThinkDigitalRepair** [comment]
According to [this page](https://forum.qt.io/topic/12502/how-to-edit-a-ui-file/3) .ui files are just plain text xml files

**Comment by justinclift** [comment]
Yeah, they are.  Not sure how to add conditional compilation to those though, unlike with the .h/.cpp files where we do that fairly often.

eg (picking a random example here): https://github.com/sqlitebrowser/sqlitebrowser/blob/87310a62e651a76c416f417855985ae9a8590008/src/Application.cpp#L66-L68

**Comment by mgrojo** [comment]
@ThinkDigitalRepair The case that you reported should be fixed in a [nightly build](https://nightlies.sqlitebrowser.org/latest/). Could you confirm that the change done in source actually converts the key name to what a Mac user expects?

The cases of tooltip defined in the ui files are pending until we get a good idea on how to translate the key names to a native name.

**Comment by ThinkDigitalRepair** [comment]
I'm only referring to the tool tip in the UI, I did check the nightly build
as of the day I reported it and it still showed the windows command in the
tool tip.

**Comment by ThinkDigitalRepair** [comment]
@mgrojo, I can check the most recent nightly

**Comment by ThinkDigitalRepair** [comment]
@mgrojo, after checking, it has been fixed in the latest nightly. Thank you .
<img width="270" alt="screen shot 2018-09-26 at 11 52 06 am" src="https://user-images.githubusercontent.com/23037821/46102241-bc11ea00-c182-11e8-8a3f-bbb22b5679a0.png">

**Comment by mgrojo** [comment]
Nice. Thank you for confirming, @ThinkDigitalRepair.
