### ISSUE TITLE
Blob data is displayed incorrectly

### ISSUE THREAD

**Issue by qiuzhiqian** [sqlitebrowser/sqlitebrowser#1846]
Details for the issue
--------------------
When I insert the blob data of invisible characters into the database, I use the software to view the data in binary mode. The data is inconsistent.

#### What did you do?
CREATE TABLE PARAM_TABLE(ID INT PRIMARY KEY     NOT NULL,NAME           TEXT    NOT NULL,PARAM          BLOB     NOT NULL)

then i insert a row into my database with sqlite c api.the blob data val is 04 D2(Decimal is 1234)

#### What did you expect to see?
04 D2

#### What did you see instead?
04 ef bf bd

Useful extra information
-------------------------
Number of characters displayed 2

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x ] 3.11.2
- [x ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by qiuzhiqian** [comment]
when i run :
$ sqlite3 param.db "select PARAM from PARAM_TABLE where ID=15" | hexdump -C
00000000  04 d2 0a                                          |...|
00000003

i can get currect hex result

**Comment by qiuzhiqian** [comment]
![2019-04-12_09-55](https://user-images.githubusercontent.com/19386888/56010075-bc379880-5d14-11e9-9f55-433a2b737364.png)

**Comment by justinclift** [comment]
This **might** be another case of #1772, which was fixed in the recent 3.11.2 release.

Would you be ok to update to the new release, and check if that works properly? :smile:

&nbsp; &nbsp; https://sqlitebrowser.org/blog/version-3-11-2-released/

**Comment by qiuzhiqian** [comment]
> This **might** be another case of #1772, which was fixed in the recent 3.11.2 release.
> 
> Would you be ok to update to the new release, and check if that works properly? 
> 
>     https://sqlitebrowser.org/blog/version-3-11-2-released/

But I did not find version-3-11-2  binary package for linux.
I build the newest source code from master branch with qtcreator.This problem still seems to exist

**Comment by justinclift** [comment]
Oops, didn't notice you're using Linux.  Sorry about that!

Compiling from `master` branch instead was correct. :smile:

> This problem still seems to exist

Thanks, that's good info.  This is probably something @mgrojo will be interested in hearing about.

**Comment by mgrojo** [comment]
#1772 still needed a bit of fine-tuning. It should be fixed now in the master branch. @qiuzhiqian, would you mind to pull the change and confirm that it's fixed for you?

**Comment by justinclift** [comment]
Wow, that was fast. :smile:

**Comment by qiuzhiqian** [comment]
oh.the source code from master branch work fine now on my pc(arch+kde+qt5.12) now.thank you. @justinclift  @mgrojo

**Comment by justinclift** [comment]
Awesome!  Thanks for verifying it and letting us know @qiuzhiqian. :smile:
