### ISSUE TITLE
Add options (toolbar) to format rows - cells into the Browse Data tab (colours etc)

### ISSUE THREAD

**Issue by SilvioGrosso** [sqlitebrowser/sqlitebrowser#1976]
Describe the new feature
--------------------------
Add an option (widget with a toolbar with many bottons) to format your rows and cells into the Browse Data tab.

I am referring particularly to the option of colouring your rows and cells.
In addition, it would be cool to also have an option to format them as well (bold, italic, underline). On top of that, ananother option might be to align your text (left, center, rigth).
Yes, you got it:  Just like a true spreadsheet (Excel, Calc etc) :-) :-)

At present, you can already change the font and size of your text (via the Preferences options). It is also possible to colour your cells through the "Conditional format".

Needless to say, this new formatting options should be saved into the Project file for future use...

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
Nope.

#### Does this feature exist in another product or project? Please provide a link.
Yep. DBeaver, which is an open source Java database manager (https://dbeaver.io/).
With DBeaver you can easily colour your rows and cells.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
I attach a screenshot of DBeaver with an Sqlite connection:

<img width="960" alt="dbeaver" src="https://user-images.githubusercontent.com/33007383/63538435-30324a80-c518-11e9-9708-07295a2ff7fc.png">

**Comment by mgrojo** [comment]
@SilvioGrosso, the next nightly build will include my progress in this feature. You can take a look to the various commits to get an idea of the functionality, but here is a summary:
- The conditional formats have been extended to include several style options.
- A collapsible toolbar has been added to the data browser. Using this toolbar you can currently modify the selected column(s) format by adding or updating a conditional format without condition (that is, a format applying to all cells in column except when other conditional format is given more precedence).
- Formats are saved to the project file.

I plan to add the following (Martin's idea):
- Take into account the formats when copying to HTML, so the work done in DB4S can then be pasted into Spreadsheets or other kind of applications.

I'm considering adding the following, given your feedback or that from other users or developers:
- Direct formatting of single cells or rows. This will need changes to the underlying conditional formats, and I'd want to know if there is enough interest in this, since I think that the most logical formatting of a DB table data is based on conditions or when applying to whole columns. But I'm open to explore the row or single cell options. How would it be used? For marking manually analyzed data? Knowing how it would be used, it's the best thing to know how to implement it.

**Comment by SilvioGrosso** [comment]
Hello @mgrojo 

> Take into account the formats when copying to HTML, so the work done in DB4S can then be pasted into Spreadsheets or other kind of applications.

It looks a good improvement indeed :-)

> I think that the most logical formatting of a DB table data is based on conditions or when applying to whole columns.

Yep. You might be right about that!
Needless to say, a table in a database is a completely different thing compared to a table in a spreadsheet :-)

IMHO, one advantage of having also an option to colours the whole rows is that it is easier to see where the "focus" must be  concentrated at first hand. 

More precisely, let's suppose:
- I have got a table with 30 columns and 5000 rows (id).
- Column 25 and 26 are Latitude and longitude (with gps data);
-  Now I want to remind my coworker to modify later the gps data of the Id from 56 to 60 (that is, 5 rows in total);
- With the conditional format I could colour the 10 cells (id from 56 to 60) of the 2 columns (5 cells of latitude + 5 cells of longitude);
- Here is the "problem" because my coworker has to scroll down to the right of the table to reach columns 25 and 26 in order to see what colour has changed...
- On the contrary if I could colour the entire rows (from 56 to 60) it would be easier (I mean fast) for him to recognize that these are the very rows where the latitude and longitude have to be changed.

To recap, in my view, *both* approaches are correct and they are complementary. 
If you think about LibreOffice Calc or Excel you have both options (conditional formats plus colouring of single rows - cells - columns) :-)

This being said, I don't know how much work this would entail and I fully agree that currently you migh consider to have much bigger fish to fry as regards the Browse data code :-)
At present, your present improvement is already a BIG step forward (thanks for working on this...).
Most of all, It is vital to NOT introduce regressions and this might be the case with my suggestions...

Unfortunately, I can't test your work (and Martin's) because there are no nightly builds available for Windows 10 (64 bit). Therefore, it is is difficult for me to judge...
See issue: 
https://github.com/sqlitebrowser/sqlitebrowser/issues/2010

**Comment by mgrojo** [comment]
There are two new features:
- The copy to clipboard includes formatting (already in today's nightly)
- The box for editing Condition in the dialog is the same as the one in the column filters and global filters. That includes a contextual menu for helping with the syntax and What's This information. It will be in tomorrow's nightly build.

My next planned step is looking at the single cell or row formatting and see whether it's simple enough to be included.

**Comment by SilvioGrosso** [comment]
Hello @mgrojo 

I think I have encountered a minor bug in the Edit format conditionals
In short, the text you write in the filter is lost when you add a new condition.
To fix this problem you have to add all the conditions and only then type your multiple conditions.

To always reproduce on Windows 10 - 64 bit (with the zip 64 bit version of Sqlite Browser):
1) Add a new filter for the column Salary(>1660);
2) Add a second condition: now my previous filter on the Salary column has disappeared (>1660 is no longer listed). 
3) I have to *retype* >1660 and the second condition e.g. < 990 to make it work

<img width="485" alt="format_conditionals" src="https://user-images.githubusercontent.com/33007383/66265213-d4472b00-e812-11e9-9be5-0a48622db807.png">



> My next planned step is looking at the single cell or row formatting and see whether it's simple enough to be included.

Yep. This would be very cool because it would pave a way to mimick the behaviour of all spreadsheets (calc, excel etc). 

But again, when I have proposed this feature I didn't know how difficult and long might be to code...
I also hope it works with the stable release of QT 5.12.X (in principle it should works fine....)

**Comment by mgrojo** [comment]
Hi @SilvioGrosso 

> I suppose I have encountered a minor bug in the Edit format conditionals.
> 
> In short, the text you write in the filter is lost when you add a new condition.

I've reproduced this bug and have fixed it. You can confirm in tomorrow's nightly build.

I've also fixed the problem that I was having when moving a line to the top. Now the other widgets are correctly placed. This might be a bug in Qt, not sure, but it is working well now.

There was also a problem in your screenshot that Martin also had: the font combo-box is not resized correctly and it overlaps the bold check button. It is now fixed to 125px and should also behave well, but this particular problem wasn't reproduced in my setup. It might also be a Qt problem.

I also want to implement asking to save changes when no project file has been opened but the user has made format changes.

**Comment by SilvioGrosso** [comment]
Hello @mgrojo 

Just tested on Windows 10 (64 bit) your bug-fixing.

>  In short, the text you write in the filter is lost when you add a new condition.
>  I've reproduced this bug and have fixed it.

Yep. I confirm it now works fine on my system.

> There was also a problem in your screenshot that Martin also had: the font combo-box is not resized correctly and it overlaps the bold check button

Unfortunately it is not fixed (Windows 10). I suppose It might be a bug related to the QT widgets.
It occurs especially as regards the bold option (since it is close to the size font culprit).
To make it work you have to drag to the right the border of the "Size" Font. 
After this scrolling all check-boxes (bold etc) to its right are available.

I have noted this little GUIs bug myself and this was the reason why I have asked about the future implementation of the QT 5.12.X LTS on Windows 10 - 64 bit. For the 32 bit version of Windows I suppose you are stuck with an older version of Qt.

See this screenshot:

<img width="598" alt="box_image" src="https://user-images.githubusercontent.com/33007383/66288431-79c4d200-e8d9-11e9-8490-560bacae9fab.png">

Here is a video recorded with more details:

https://www.dropbox.com/s/5hsc4pz6k7ksq8s/FILTER-CHECK-BOX.mp4?dl=0

As usual, thanks a lot for your efforts :-)

**Comment by mgrojo** [comment]
I have requested a maximum width for the font combo box. Let's see if this works around the problem in tomorrows nightly. Yes, it's probably a bug in Qt that could be fixed in the last Qt release, but I don't have a Windows environment to try changes in the nightly compilation.

**Comment by justinclift** [comment]
That reminds me.  The Qt version on our nightly build box VM's is overdue for updating.  Will get that updated some time in the next few weeks. :smile:

**Comment by scottfurry** [comment]
@justinclift - 5.12.5 looks good at the moment. That appears to be latest LTS for 5.12 series. Don't expect bleeding edge 5.13 yet.

**Comment by SilvioGrosso** [comment]
Hello @mgrojo 

Just tested both the 32 and 64 versions on Windows 10 (64 bit).
The 32 bit version with QT 5.7.1
The 64 bit version with QT 5.11.3
This very **minor** graphical bug is still present in both versions (QT 5.7.1 and QT 5.11.3).

Maybe the QT 5.12.X LTS version has this problem already fixed. However, quite likely, you risk to introduce new *different* bugs - regressions as well :-)
I have proposed to switch to the QT 5.12 in the future because it is a  LTS version; because at least you might file some bugs reports upstream for a LTS version; because Krita has already switched to this version and the developers of QGIS, a GIS open source, are considering this change as well.

Do *NOT* waste your time trying to fix this minor irritance!
At present it is very easy to fix it manually by the end user and it only occurs when you add the first condition with the conditional filters.
Since it works on Linux it is fine for me as well. 
I am testing on Windows 10 because I run myself mostly Windows even though in my spare time I also work on Kubuntu (KDE distro).

Working with graphical toolkits (Qt, gtk, WxPython) you always get these kind of problems :-)
The trick to avoid these nasty headaches, by fixing the graphical bugs, would be to force every user to work on the  Sqlite command line. The same you might do with PostgreSQL by leveraging the psql command line. By doing so, you would not have to fight with the QT toolkit. However, I DO suppose you would not have any user left to test your Db browser software in the end:-)
And *YES* you might even try to force every Windows user to switch to Linux (kde - gnome, mint etc) but this has failed to succeed in the last decade and I do suppose it might fail in the future as well :-)

Here is the screenshot with today's 64 bit (zip) - nightly version:

<img width="483" alt="format_bug" src="https://user-images.githubusercontent.com/33007383/66455576-76f9e680-ea6b-11e9-804f-79e375a316ee.png">

**Comment by justinclift** [comment]
Updating Qt in the Windows build VM to Qt 5.12.5 )MSVC 2017 x64) now.  Lets see how it goes... :wink:

**Comment by justinclift** [comment]
Adjusted out Win64 nightlies to use the newly installed Qt 5.12.5 on the build VM, then rebuilt todays one's.

Anyone up for testing?

* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.msi
* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.zip

**Comment by SilvioGrosso** [comment]
Hello @justinclift 

Just tested both new installers on Windows 10 - 64 bit.

The little bug regarding the Edit conditional Formats is still there BUT, strangely enough, *both* win64 versions (zip and msi) report the QT version 5.11.3 in the about window. 
At first I have thought it was my fault but I have double-checked several times and they are always listed indeed as the prior QT version (not the LTS 5.12.5).

Here is the mandatory screenshot:

<img width="328" alt="old_version" src="https://user-images.githubusercontent.com/33007383/66507389-64b19400-eacf-11e9-88ac-bc16f2a30b1f.png">

**Comment by justinclift** [comment]
Hmmm, sounds like the build failed after all and those are the original binaries from yesterday. :frowning:

Interesting.  Will investigate. :smile:

**Comment by justinclift** [comment]
Looks like the qtquick1 translation files aren't in Qt 5.12, so the build process was dying at the end when doing the Wix packaging.  Just pushed a fix which seems to work, and there's a new Win64 build on the nightlies server now using it. :smile:

**Comment by SilvioGrosso** [comment]
Hello @justinclift ,

Thanks a lot indeed!
As soon as they are ready, I am going to test them in depth :-)

Today, I have tested much more the last nigthly build (QT 5.11.3) on Windows 10 (64 bit).
There are some little bugs concerning the GUIs related to the DB browse. 

Perhaps they are not reported so far because most users work mostly with the EDIT SQL tab, on Linux.
This is just to say that even if the QT 5.12.5 does not fix any previous bug related to the GUIs, there is also the QT 5.11.3 which is very FAR from being rock solid right now on Windows 😄

Unfortunately, the Calligra Office suite [1] is no longer actively developed. Therefore, there are a few users and developers that file bug reports upstream to the QT developers concerning these "similar" problems with tables. For instance, their spreadsheet named "Sheet" would be extremely useful to test the Qt toolkit 😄

[1] https://www.calligra.org/

**Comment by SilvioGrosso** [comment]
Hello @justinclift 

Just tested the nightly builds on Windows 10.
Now the Qt version is the LTS. *Thanks* a lot indeed for your update:

<img width="328" alt="5 12" src="https://user-images.githubusercontent.com/33007383/66628202-69289a80-ebfe-11e9-89cc-72fddc3b0737.png">

I have tested this LTS version and it looks as stable as the previous one.
I didn't notice any regressiona but of couse I need much more time to make sure this is indeed true...
Unfortunately, all little bugs related probably to the GUIs are still here (no difference between 5.11.3 and 5.12.5 in short). But in *all true* I was expecting this... 😄

I am a long time user of the Krita software (QT toolkit) and I know for sure that they are continually forced to fix themselves, in their own C++ code, the bugs related to Qt. This being said, they did opt to use the 5.12.x currently...
In essence, for the Krita developers the stablest version for QT is Linux > Windows > Mac. This last one is by far the worst one to work with Krita.

**Comment by justinclift** [comment]
Ahhh. Looks like the quick hack to get the Win64 build working, incorrectly specified things for Win32, thus breaking that one's build.  Knew I should have tested it, but had limited time.

Will fix, but probably tomorrow instead of now.

**Comment by SilvioGrosso** [comment]
Hello @justinclift 

As far as I am concerned I have never used the Windows 32 builds these past years (they would defeat the purpose of having and Intel I7 CPU with 8 gb RAM) 😄

In all truth, considering the trouble you have to create them daily and the space they take on your servers, I even personally think you should drop them in the future, *after* the next stable version is released...

At present some Open source softwares have already stopped producing them.
In the end, if you want to work with some specific 32 bit software you can always download some old versions (where the 32 bit are still available)...

**Comment by justinclift** [comment]
Meh, they're not much hassle and they mean people using older systems can still use modern DB4S. :smile:

**Comment by SilvioGrosso** [comment]
Hello @mgrojo 

Just downloaded the latest nightly build (Qt 5.12.5 LTS).

I *know* it is still a work in progress therefore, please, bear with me for this rush :-)

At present,  I don't understand how to colour only a row or a single cell. 
Whenever I try to color something either all table is colored or the whole column. 
With Calc or Excel I only need to pick a cell  or some rows and pick some colors but, I suppose, it is not the same way as it has been  implemented right now on Db Browser:-)

**Comment by mgrojo** [comment]
That is not working as expected. I have seen a compilation error sent by
Travis, so maybe the nightly hasn't been generated. I'll take a look later
at home.

**Comment by mgrojo** [comment]
@SilvioGrosso I've just used wine to test with this nightly build:
[DB.Browser.for.SQLite-win64.zip](https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.zip)                    28-Oct-2019 04:21            18727506

It works as I expect; you select a cell and press any of the formatting buttons and it is applied to that cell. For applying the style to:
- An entire row: select the row (for example, using Shift+Space) and press a format button.
- An entire column: select the column (for example, using Ctrl+Space) and press a format button. The format applies to new cells in the column, because it is associated to the column.

For defining a new conditional format, there are now three methods:
- Use a filter and the use the contextual menu in the filter box for creating a new conditional format with an automatic background colour for that filter.
- Use a filter and select the entire column, and then press a format button. The format is applied to the column using that filter as condition (new method).
- Use the dialog to create manually new conditional formats.

Isn't working for you like that?

**Comment by mgrojo** [comment]
The compilation error was only affecting to the Travis build due to the Qt version used there, but not to the nightly build. It is already corrected, nevertheless.

**Comment by SilvioGrosso** [comment]
I have tried with the build you linked and everything works extremely well!
No crash whatsoever either!
I have saved and reopened a project and all changes are still present.
In short, it is indeed a TOP NOTCH implementation!

Thanks a lot indeed: now Db Browser is much more similar to a spreadsheet which can be quite handy for casual users who are usually much more used to work with this kind of applications at home - work.

BTW, I have noted that if you copy a cell with a formatting applied and you past it into a different cell the formatting is not copied. This is completely fine IMHO (NO need to change this behaviour).

BTW, There is no fast undo-redo implemented (ctr-z and ctr-y) but, again, this is NOT necessary in the end. Therefore, there is no real need to implement it IMHO.

Here is the mandatory screenshot:
<img width="960" alt="screen" src="https://user-images.githubusercontent.com/33007383/67717656-726f8080-f9ce-11e9-9c4e-f82e3e56d0c2.png">

**Comment by MKleusberg** [comment]
Looks like this is more or less finished :smile: So I'm going to close this issue in preparation of the next release.

**Comment by rik1301** [comment]
Mrgrojo - I've just been trying the toolbar and discovered an issue (I think).  My grid view text is set to Verdana 10pt however when I open the toolbar it has Ms Shell Dlg 2, 8pt set.  Should it not reflect the settings I have set in my preferences rather than the program default?  I can change it back to Verdana 10pt for a given row/cell, but when I want to format a different one it reverts back to Ms Shell again.

As a side question, is it not possible to bold/italic specific words within a cell?  I have tried but it does the entire cell contents.

**Comment by justinclift** [comment]
@mgrojo ^^^

**Comment by chrisjlocke** [comment]
> As a side question, is it not possible to bold/italic specific words within a cell? I have tried but it does the entire cell contents.

No, as you're viewing data, so the bold/italic is just changing the view of that data.
There is no 'standard' way of displaying formatted text - HTML has tags, RTF has convoluted code, Word DOC formats have magic fairies and .... well, you get the idea.  You can't 'bold' a word in a cell as there is nothing to bold - how would it format it to display it as bold, without changing that data?

So, short answer - No.

**Comment by rik1301** [comment]
Chris Locke: thank you for your reply.  I received it in my emails, but for some reason it hasn't populated here.

**Comment by chrisjlocke** [comment]
No, I realised I was talking complete goo goo, so deleted it, as it wasn't relevant to the issue.

**Comment by mgrojo** [comment]
> Mrgrojo - I've just been trying the toolbar and discovered an issue (I think). My grid view text is set to Verdana 10pt however when I open the toolbar it has Ms Shell Dlg 2, 8pt set. Should it not reflect the settings I have set in my preferences rather than the program default? I can change it back to Verdana 10pt for a given row/cell, but when I want to format a different one it reverts back to Ms Shell again.

Yes, that was a bug and it will be solved in the next nightly build.

> 
> As a side question, is it not possible to bold/italic specific words within a cell? I have tried but it does the entire cell contents.

No, it is not currently possible and probably never be. Take into account that the format is metadata applied to the database and stored in a project file. 
Applying different formats to the data inside a cell means that it would have to be saved as cell data in the database itself and that would interfere with the user data.
