### ISSUE TITLE
Cannot install sqllitebrowser

### ISSUE THREAD

**Issue by olashano** [sqlitebrowser/sqlitebrowser#2251]
Details for the issue
--------------------

#### What did you do? This software needs to be updated. Contact the developer for more information.

This item is on the disk image “DB.Browser.for.SQLite-3.12.0-alpha1.dmg”. Safari downloaded this disk image today at 3:26 PM from github-production-release-asset-2e65be.s3.amazonaws.com.

#### What did you see instead?

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.12.0-(alpha or betas)
- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by olashano** [comment]
“DB Browser for SQLite” can’t be opened because Apple cannot check it for malicious software.

**Comment by olashano** [comment]
Fixed it.

**Comment by scottfurry** [comment]
For others that search for this problem, see this [Apple Support article](https://support.apple.com/en-us/HT202491)

**Comment by cminton** [comment]
I still get the Apple error. “DB Browser for SQLite” can’t be opened because Apple cannot check it for malicious software.

**Comment by justinclift** [comment]
@cminton Someone on Twitter was mentioning the same thing yesterday.  Apparently there are steps in the above Apple Support article which got it working. :smile:

**Comment by cminton** [comment]
Thanks. I saw that and it did work.

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by john-kurkowski** [comment]
What is the conclusion from that article? Manually bypass all macOS security checks for this 1 app?

What do you think about fixing the root cause? Do whatever you need to allow Apple to "check it for malicious software."

**Comment by justinclift** [comment]
Yeah, we need to get some stuff done for the next release. :smile:

With the article, it's pretty much saying when you try to run an application that hasn't been "Notarized", it'll be blocked + listed in the `Security and Privacy` tab of macOS System Preferences.

In that tab, you can give access for that specific application to be launched.  It'll then work the next time (and onwards) you try to launch it.
