### ISSUE TITLE
Font change in Browse Data table is not carrying over to Edit Database Cell

### ISSUE THREAD

**Issue by oryxius** [sqlitebrowser/sqlitebrowser#2295]
Hello everyone,

I use the DB Browser for a research project and a student of mine who updated to the latest version (on a Mac computer) reported a font bug in it. So I updated my version and noticed the same on my Windows machine. Basically, in the past we used to choose a specific font ("Sakkal Majalla" in my case on Windows) to use for both English and Arabic in the Browse Data table and the Edit Database Cell window. It used to work in both. After the update, the Edit Database Cell reverted to the system font and I found no way to change it back.

Thank you,

Muhamed Al Khalil
Professor in Arabic Studies
New York University

**Comment by mgrojo** [comment]
Thanks for reporting it. I've made a change that should fix that and come back to the former behaviour. Could you please confirm it using [tomorrow's nightly build](https://nightlies.sqlitebrowser.org/latest/)?

**Comment by justinclift** [comment]
If that fixes the problem, we should apply it to 3.12.1 as well. :smile:

**Comment by oryxius** [comment]
Thanks. I don't know if I should wait till tomorrow to run the build you
sent. But I ran it anyway, and it still shows the same problem. Let me know
if I should wait and try again tomorrow.

Best,

M. Al Khalil

**Comment by justinclift** [comment]
> Let me know if I should wait and try again tomorrow.

Yeah.  Our nightly builds start being created at around midnight GMT.  It takes a few hours for everything to complete... so they'll be ready probably 6 hours or so from now onwards. :smile:

**Comment by chrisjlocke** [comment]
Just went to check the nightly build, and on Windows, this seemed to be working anyway...

![image](https://user-images.githubusercontent.com/7872218/85407344-047a5980-b55b-11ea-8851-e8b346cd8ea4.png)

So changed the font to 'Script' and the 'edit database cell' (for text, anyway) changed.
This also occurred on program startup, and not just when the font was changed.  
So I don't know if the code you added was a duplicate, or a fix for other operating systems, but 3.12.0 seems OK on Windows...

As a nod, the nightly does the same too, so the additional code hasn't broken anything either ;)

**Comment by oryxius** [comment]
Hello everyone,

Yes, I can confirm that the updated nightly version is working fine now
after the fix.

Many thanks for the prompt actions.

Best,

M. Al Khalil

**Comment by mgrojo** [comment]
That's because you don't write in Arabic. Try setting the Mode manually to
RTL Text and you'll see the difference. When I restored the Qt editor
widget for right-to-left languages I forgot about this part.

**Comment by justinclift** [comment]
@mgrojo Should this go into 3.12.1?

**Comment by mgrojo** [comment]
> @mgrojo That response was to @chrisjlocke's now-deleted comment yeah?

Yes, I forgot to mention him or quote the message.

> 
> Also, should this go into 3.12.1?

Yes, added the corresponding label. We can later review the change and cherry pick all those which are simple fixes of problems present in 3.12.0.
