### ISSUE TITLE
Small bug causes crash

### ISSUE THREAD

**Issue by AndreasMartin72** [sqlitebrowser/sqlitebrowser#233]
Starting application with no database open, a click on the "save file" icon on the "Execute SQL" button then leads into crash. 
Anyway, great piece of code. Thank you!

**Comment by justinclift** [comment]
Yep, just confirmed it on OSX 10.9 with our latest code. :wink:

Thanks for pointing it out. :smile:

**Comment by samir-aguiar** [comment]
This should be fixed now, thanks! :)

**Comment by justinclift** [comment]
Thanks @samir-aguiar, tried it here and it seems good to me.  @AndreasMartin72 Do you have a few minutes to verify it's working properly now for you too? :smile:

**Comment by AndreasMartin72** [comment]
Hi Justin,
 
I took the version from 21.03.2015 (http://rp.oldsch00l.com/sqlitebrowser/), the problem still occures...
 
Regards,
Andreas
 
 
-----Ursprüngliche Nachricht-----
 Von: "Justin Clift" [notifications@github.com]
 Gesendet: Sa. 21.03.2015 21:42
 An: "sqlitebrowser/sqlitebrowser" [sqlitebrowser@noreply.github.com]
 Kopie: "AndreasMartin72" [andi.martin@freenet.de]
 Betreff: Re: [sqlitebrowser] Small bug causes crash (#233)

Thanks @samir-aguiar, tried it here and it seems good to me.  @AndreasMartin72 Do you have a few minutes to verify it's working properly now for you too? 
—
Reply to this email directly or view it on GitHub.
-----Ursprüngliche Nachricht Ende-----


---
Alle Postfächer an einem Ort. Jetzt wechseln und E-Mail-Adresse mitnehmen! Rundum glücklich mit freenetMail

**Comment by justinclift** [comment]
Oops yeah, you'd need to wait until tomorrow because the nightly build process hasn't run yet. :smile:

**Comment by AndreasMartin72** [comment]
Re: [sqlitebrowser] Small bug causes crash (#233)



Hi Justin,

yes, now it's ok, thank you!

Cheers,
Andreas





Oops yeah, you'd need to wait until tomorrow because the nightly build process hasn't run yet. 
—
Reply to this email directly or view it on GitHub.





-- 
Grüße,
Andreas Martin
mailto:andi.martin@freenet.de

**Comment by justinclift** [comment]
Awesome.  Thanks for testing it and getting back to us Andreas. :smile:
