### ISSUE TITLE
The database you are trying to delete is currently opened. ...

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#2334]
Trying out the latest "Remote" pane pieces now.

The ability to remove locally downloaded databases should be really useful. :smile:

Did notice one minor, and one trivial, problem with it.

The dialog shown "The database you are trying to delete is currently opened" isn't always correct.

I **did** try and delete the currently open database, just to see if it would work.  The dialog was correctly shown then.

Right after that though, I clicked the "Close database" button to close it, and tried deleting it again.  The same dialog "The database you are trying to delete is currently opened..." dialog was displayed. :wink:

---

In the new "Current Database" tab, which shows details for the open database.  After closing the currently open database, the drop down list of branches is still populated with the old info (eg "master").  Guessing that should be cleared as well?

**Comment by MKleusberg** [comment]
Should be fixed :smile: Can you give it another try?

**Comment by justinclift** [comment]
Good stuff. Yep, both are fixed now. :smile:

While trying it out, one minor (but annoying), usability thing crops up.  The wdith of the "Name" field in the main "DBHub.io" tab is quite narrow by default.  Needs to be manually dragged out wider every time DB4S is opened in order to see the database names.

Is it fairly to change that default width to be wider?  Maybe autosize it on loading to accommodate the widest database name?

**Comment by MKleusberg** [comment]
I've just made a bit wider by default (while also making some other improvements to the tables). It's still not autosized because with the current approach which loads the database names only when needed it would make the column width jump around every time a directory is opened. But with the wider name column it should be a lot better already :smile:

**Comment by justinclift** [comment]
Just tested, and yep, the new default width is a lot better now.  Thanks heaps. :smile:
