### ISSUE TITLE
Character Encoding issue at 'Execute SQL' panel

### ISSUE THREAD

**Issue by jimmyp2** [sqlitebrowser/sqlitebrowser#311]
Hello,
trying to type Non-English characters and more specifically Greek at the 'Execute SQL' panel or trying to load an SQL file containing Greek characters they appear as English language question marks( ? ). Why is this happening ? I would like to note that data containing Greek characters stored in the database's tables are presented correctly in the Grid when a select statement is executed at the 'Execute SQL' panel. See attached picture for an example of what is going on.

Thank you very much.

Sqlite Browser version used : 3.6.0
OS: Windows 8.1 Pro English 32bit

![pict1](https://cloud.githubusercontent.com/assets/12430967/7614224/1f5199ea-f99e-11e4-8f04-a9666a57a12b.jpg)

**Comment by justinclift** [comment]
Ahhhh, I think this is a bug we fixed a few days ago: https://github.com/sqlitebrowser/sqlitebrowser/issues/282

Would you be ok to try out our latest nightly build (locations are listed on our front page), and see if that works?

**Comment by justinclift** [comment]
@jimmyp2 ping?

**Comment by jimmyp2** [comment]
Hi again,

thanks for the quick response and sorry for the delayed comeback.
Well, the problem is partially fixed using the nightly build suggested. Now typing Greek characters directly at the 'Execute SQL' panel works as expected but the problem remains when trying to load an SQL file containing Greek characters that is saved using the default Windows ANSI encoding - if it's saved as UTF-8 then it loads properly(Greek characters are shown correctly). This is a minor issue but it would be nice to work either way. I say this because working also with other databases like MS Sql Server for example loading the same SQL file in Sql Server Management Studio using either encoding(ANSI or UTF-8) files are loaded without issues.

Thank you very much.

**Comment by justinclift** [comment]
Oh that's interesting.  Sounds like we have a bit more stuff to do for this, to properly complete it.

**Comment by hamidmalek** [comment]
hi there, I can't write persian words in sql panel and I don't know what should I do? help me please.

**Comment by justinclift** [comment]
@hamidmalek Try using our latest "nightly build".  The download location is on the front page of our repo.

If that doesn't work, then let us know. :smile:

**Comment by justinclift** [comment]
@schdub @MKleusberg Any interest in looking at this? :wink:

**Comment by MKleusberg** [comment]
@justinclift Just tried it with the latest build and it works. So I assume using the nightly build it'll work for @hamidmalek , too. If not it might be necessary to set another font in the Preferences Dialog. The only thing I noticed is that especially selecting text is a bit erratic because of the mix of LTR SQL text and RTL Farsi text but that doesn't seem to be much better in other applications...

**Comment by justinclift** [comment]
Awesome.  Thanks Martin. :smile:

**Comment by mgrojo** [comment]
> the problem remains when trying to load an SQL file containing Greek characters that is saved using the default Windows ANSI encoding - if it's saved as UTF-8 then it loads properly(Greek characters are shown correctly). This is a minor issue but it would be nice to work either way. I say this because working also with other databases like MS Sql Server for example loading the same SQL file in Sql Server Management Studio using either encoding(ANSI or UTF-8) files are loaded without issues.

That can be solved using the encoding option inside the contextual menu of the column header. I'll close this as it is very old, and I think there's no issue, but feel free to reopen it if version 3.13.0 still has some problem with Greek.

Regarding Farsi and other LTR languages, we also have #884.
