### ISSUE TITLE
[Bug]: Table definition not recognized if constraint name defined as string

### ISSUE THREAD

**Issue by phidrho** [sqlitebrowser/sqlitebrowser#3199]
### What did you do?

I created tables with named constraints with name defined as string value and DB Browser for SQLite reports:
`Warning: There is something with this table definition that our parser doesn't fully understand. Modifying and saving this table might result in problems.`.
Other software doesn't have problem with this type of name constraint definition and therefore I'm supposing it's a valid DDL query.

Other software I tested: official sqlite-tools, sqlite-gui and SQLiteStudio.

### What did you expect to see?

Properly read DDL with name for named constraint defined as string value.

![sqlite-tools](https://user-images.githubusercontent.com/1849293/197409191-7a19c248-2a0e-40a9-84f2-892947e870ef.png)

![sqlite-gui](https://user-images.githubusercontent.com/1849293/197409214-b58e5a12-ee0e-4e9e-b609-cb382ad562ed.png)

### What did you see instead?

Software doesn't see table definition and reports a warning.

You can test with:

```sql
DROP TABLE IF EXISTS TABLE1;
CREATE TABLE TABLE1	(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	TEXT_FIELD TEXT NOT NULL,
	CONSTRAINT un_constraint UNIQUE (TEXT_FIELD)
);

DROP TABLE IF EXISTS TABLE2;
CREATE TABLE TABLE2	(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	TEXT_FIELD TEXT NOT NULL,
	CONSTRAINT 'un_constraint' UNIQUE (TEXT_FIELD)
);

DROP TABLE IF EXISTS TABLE3;
CREATE TABLE TABLE3	(
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	TEXT_FIELD TEXT NOT NULL,
	CONSTRAINT 'un-constraint' UNIQUE (TEXT_FIELD)
);
```

After successful SQL execution, DB4S doesn't see `TABLE2` nor `TABLE3`.

![Database structure](https://user-images.githubusercontent.com/1849293/197409113-6652f200-6cd9-4e5f-8a96-7d3d692ae513.png)

![Browse data](https://user-images.githubusercontent.com/1849293/197409134-e5f84972-4ae2-4935-8256-c48f89cff350.png)

![Edit table definition](https://user-images.githubusercontent.com/1849293/197409309-3f240b82-8cfb-4df7-82a9-a18b0b9dbc50.png)

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
If you try the nightly (always worth trying the nightly...) you'll see this issue has been resolved.

![image](https://user-images.githubusercontent.com/7872218/197416220-024d2354-270b-4a49-80bd-1f9c45c880f6.png)


The nightly (always worth trying the nightly...) can be downloaded from here:
https://nightlies.sqlitebrowser.org/latest/

If you download the nightly (always worth trying the nightly...) you can just extract the .zip and run the .exe - don't have to install, and it won't affect the current installed version.

**Comment by phidrho** [comment]
Hi @chrisjlocke,
thank you for checking nightly build.

Bug is still present in current version though, and nightly builds are not considered stable.
Since I didn't found bug report for this bug when I was searching for it, I think it is good to leave it open until new version is released, but that's a developers decision.

**Comment by chrisjlocke** [comment]
As I explained, this is resolved in the nightly - I showed that with my screenshot.

The nightly in this instance is stable enough (bar project files) to resolve your situation.

In this instance, I'll close this as the issue is resolved, but if you encounter it when the next version is released, you are more than welcome to open it again. :)
