### ISSUE TITLE
[Bug]: IntelliSense not working

### ISSUE THREAD

**Issue by rgmiller2** [sqlitebrowser/sqlitebrowser#3706]
### What did you do?

Writing SQL queries in Execute SQL pane. Project and database loaded and queries working. However IntelliSense is not bringing up tables or fields. It does display some code suggestions. I do have code completion turned on.

### What did you expect to see?

Inline suggestions for tables or fields while typing query.

### What did you see instead?

No suggestion.

### DB4S Version

3.13.0

### What OS are you seeing the problem on?

Windows

### OS version

Windows 11 Home

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
All databases, or just one?  Sometimes, a wonky table can stop DB4S reading the full database schema.

![image](https://github.com/user-attachments/assets/76e35079-f18a-4368-8a8b-a2da0e39a562)

So this works for me.
What I'd try is creating a new database.  Does it work?
Export the schema of your database where it doesn't work, so you've just the tables.  Does it work?  I assume not, so one by one, remove tables until it does work.  Theoretically, you can then find the table it doesn't like.
If that sounds like waaaaaaaaaaay too much work, simply email the database schema (so no data) to issue3706 [at] chrisjlocke [dot] co [dot] uk and I can have a fiddle...

**Comment by rgmiller2** [comment]
Thank you chrisjlocke for the advice. I will give that a try as soon as I can get back to my office.

**Comment by mgrojo** [comment]
Oops, this is happening for tables for which v3.12 worked like a charm, so we have broken something at some point... Example, [northwind](https://raw.githubusercontent.com/jpwhite3/northwind-SQLite3/main/dist/northwind.db) database.

**Comment by mgrojo** [comment]
Here is a workaround, go to Database Structure (Alt+D) and press F5 to refresh the database schema. After that, the autocompletion will work again

**Comment by justinclift** [comment]
Might be a race condition then, with the intellisense code not running at the correct time for newly opened databases?

**Comment by mgrojo** [comment]
> Might be a race condition then, with the intellisense code not running at the correct time for newly opened databases?

Probably. And I think this has happened before.

**Comment by rgmiller2** [comment]
> All databases, or just one? Sometimes, a wonky table can stop DB4S reading the full database schema.
> 
> ![image](https://private-user-images.githubusercontent.com/7872218/357951426-76e35079-f18a-4368-8a8b-a2da0e39a562.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTI4MjMsIm5iZiI6MTcyNDU5MjUyMywicGF0aCI6Ii83ODcyMjE4LzM1Nzk1MTQyNi03NmUzNTA3OS1mMThhLTQzNjgtOGE4Yi1hMmRhMGUzOWE1NjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjVUMTMyODQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWJjZDk3NmI4MzRlZjlkNDYzOWQ0NTEzYWYzNzhkZDdiYTdhM2RkMjhmZmM5M2U2MTE3ZDc2Y2VhMTBlZTlhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6pXaGD9l_Fp6X1ghaH4BB0yYzyjvECR-qsgmBQtgxR4)
> 
> So this works for me. What I'd try is creating a new database. Does it work? Export the schema of your database where it doesn't work, so you've just the tables. Does it work? I assume not, so one by one, remove tables until it does work. Theoretically, you can then find the table it doesn't like. If that sounds like waaaaaaaaaaay too much work, simply email the database schema (so no data) to issue3706 [at] chrisjlocke [dot] co [dot] uk and I can have a fiddle...

Thank you, but this did not work.  I am going to try a fresh install of DB Browser.

**Comment by rgmiller2** [comment]
I reinstalled BB Browser and started my project over. Now it is working.

**Comment by mgrojo** [comment]
There's something wrong, in any case, so I'll reopen the issue.

What I've seen is just restoring the defaults in preferences, solves the issue.

But it appears again if you check the option "Automatically load the last opened DB at startup". Is it the same for you, @rgmiller2 ?

**Comment by rgmiller2** [comment]
> There's something wrong, in any case, so I'll reopen the issue.
> 
> What I've seen is just restoring the defaults in preferences, solves the issue.
> 
> But it appears again if you check the option "Automatically load the last opened DB at startup". Is it the same for you, @rgmiller2 ?

Yes. The problem reappeared after I made some setting changes and started working:(

**Comment by sandman7920** [comment]
@rgmiller2 Please try the latest continuous build.

**Comment by mgrojo** [comment]
@sandman7920 with the master branch 31d208890521f728d48266290ebd071cfd4fdbde, it still happens for me when autoLoadLastDBFileAtStartup applies.

**Comment by sandman7920** [comment]
@mgrojo  Very strange, what platform and Qt version.

I just pushed another commit which will skip auto-load if we have a file set from CLI.

**Comment by mgrojo** [comment]
> @mgrojo Very strange, what platform and Qt version.

> DB Browser for SQLite Version 3.13.99 (Aug 28 2024)
> Last commit hash when built: 31d20889
> 
> Built for x86_64-little_endian-lp64, running on x86_64
> Qt Version 5.15.3
> SQLCipher Version 3.4.1 (based on SQLite 3.15.2).
> 

> I just pushed another commit which will skip auto-load if we have a file set from CLI.

I'll try again shortly.

**Comment by mgrojo** [comment]
Still happening with b19bbb92522dde3516a6566ecba5e23347cfc344. It seems the race condition is still there, and it depends on platform or Qt version to reproduce it or not.

**Comment by sandman7920** [comment]
@mgrojo I have done some more testing.

**Tests**
- Arch KDE Plasma 6  Qt 5/6 wayland, Xorg: **pass**
- Ubuntu  20.04 Qt 5 Xorg: **pass**
- Windows 10  Qt 5/6: **pass**
- Windows 11  Qt 5/6: **pass**
- Mac mini M2 14.6 Qt5: **pass**

Is `Preferences->SQL->Code Completion`  checked for your case?

**Comment by mgrojo** [comment]
@sandman7920 then it's probably something different. Are you building optimized or for development? I cannot check now my case, but probably is unoptimized.

**Comment by sandman7920** [comment]
> @sandman7920 then it's probably something different. Are you building optimized or for development? I cannot check now my case, but probably is unoptimized.

I have tested both.
Also, I have checked the packages generated from continuous builds.

**Comment by mgrojo** [comment]
@sandman7920 then it's probably something different. Are you building optimized or for development? I cannot check now my case, but probably is unoptimized.

Code completion is active. In fact, any refresh of the DB structure fixes it.

**Comment by lucydodo** [comment]
My heart is a little heavy because the features I've added have caused bugs. :(
On a separate note, I've confirmed that the latest continuous build has fixed the issue as well, and thanks for your hard work.

**Comment by sandman7920** [comment]
Just tested from 3.12.0 to master, the issue exists in all of them but it's harder to reproduce.
Start executable Ctrl+1 then Ctrl+1 again, auto completion doesn't work.

**Comment by mgrojo** [comment]
> My heart is a little heavy because the features I've added have caused bugs. :(

Don't worry, @lucydodo. That's the life of the SW engineer, and as you have seen, the bug was already there, waiting good conditions to happen.

@sandman7920, I cannot reproduce the issue with [DB.Browser.for.SQLite-dev-b19bbb9-x86.64.AppImage](https://github.com/sqlitebrowser/sqlitebrowser/releases/download/continuous/DB.Browser.for.SQLite-dev-b19bbb9-x86.64.AppImage). But I cannot say the same for my own build of the same commit. I still reproduce it from the command line and from the last opened DB trigger. I don't have time to investigate it, but, anyway, if it makes it more difficult to reproduce, it's already a gain.

**Comment by sandman7920** [comment]
@mgrojo  The AppImage does not ship the Qt Wayland plugin and uses Xwayland(xcb plugin) on wayland compositors.
Are you on Wayland with mutter?

**Comment by sandman7920** [comment]
@mgrojo Confirmed it's a GNOME Mutter problem, I have pushed a new commit. When you have time please test.

**Comment by mgrojo** [comment]
> @mgrojo Confirmed it's a GNOME Mutter problem, I have pushed a new commit. When you have time please test.

You nailed it. It's working now with this last commit.

**Comment by mgrojo** [comment]
@sandman7920 I feel you've gained a lot of insight on how the application starts and processes events. Maybe this other little glitch we have from a long time ago is easy now for you: #2567 :smiley:

**Comment by sandman7920** [comment]
I will revert all workarounds. I found the actual bug.
**autocompleteApi->prepare()** runs in different thread :)
https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/SqlUiLexer.cpp#L198

**Comment by mgrojo** [comment]
Commit 1fa0eb9acebeb0813b0bc6dcc3aa872ce1da9c57 works for me too. Much more elegant now.
