### ISSUE TITLE
Edit box is not updated at all (as in 'Browse Data') when in 'Execute SQL'

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#481]
To reproduce:

Type some SELECT into the SQL and execute it (BTW, CTRL-ENTER does not work for that, only F5 -- this is another issue).

The result will show up in a grid box, but going to the cells will not update the Edit Box (even though in read-only mode just like a View)

**Comment by justinclift** [comment]
Oh, that's not good.  @MKleusberg, another one for you. :wink:

**Comment by MKleusberg** [comment]
Just tested this using the latest version and it seems to work. I think we've fixed this quite some time ago to be honest. Are we ok to close this issue? :smiley:

**Comment by justinclift** [comment]
Hmmm, not sure.  @tonypdmtr ?

**Comment by tonypdmtr** [comment]
Still does not work with the keyboard -- moving from cell to cell does not update the edit box.  It only with mouse clicks.

The CTRL-ENTER issue is OK.

(BTW, what happened to the statically built daily releases?)

**Comment by justinclift** [comment]
@tonypdmtr We had to drop the statically built window's nightlies a few months ago, as we changed to use Qt5 only.  The static builds relied on Qt4, so that approach no longer worked.

Thus new nightlies.  Dynamic builds though.  The build script we use for Windows is here:

&nbsp; &nbsp; https://gist.github.com/justinclift/11cc926f214e882c8162f97c53929c07

If you have ideas on how to tweak/change it to make things better, we're open to improvements. :smile:

Note - It looks more complicated than it is, as it runs through twice.  Once for Win32, and once for Win64.

**Comment by justinclift** [comment]
@tonypdmtr Reading through your original report for this... I think we might have been misunderstanding it.

When running a SQL query in the "Execute SQL" tab on yesterdays's nightly OSX build, the results should show up in the window pane below.  I didn't personally think the result pane was hooked up to the "Edit Database Cell" er.. dockable window thing :wink: at all, but you're right.  When I click on one of the results with the mouse, it shows up in the "Edit Database Cell" window:
![screen shot 2017-05-17 at 19 28 35](https://cloud.githubusercontent.com/assets/406299/26169871/1d925568-3b37-11e7-91e5-c1775442ed37.png)
But, moving around the result pane cells with the keyboard doesn't change what's shown in the "Edit Database Cell".

I guess we need to think whether over whether things from the result pane should be shown there or not, and either unhook things (eg so mouse click doesn't show results there), or properly-hook-things up (eg including the keyboard).

**Comment by tonypdmtr** [comment]
Well, I didn't say it should be editable.  However, the reason IMO you need the read-only edit box is because long cell contents are easier to read that way, rather than directly from the grid cell.

**Comment by justinclift** [comment]
Ahhh, that makes good sense.  Hadn't thought of it that way at all.

Yeah, we should probably hook up the keyboard keys with the Edit Database Cell contents there too then.

**Comment by MKleusberg** [comment]
Thanks for the detailed explanation, @tonypdmtr :smile: I've just changed the code to allow include selection via keyboard, however it's not that easy as you can see [here](https://doc.qt.io/qt-5/qabstractitemview.html#activated). On some platforms you'll need to press Enter to trigger the action, i.e. first change the selection by using the arrow keys, then press Enter to show the contents. I'm not sure either what they mean by "depends on the platform"

Anyway, what do you reckon? Is the new approach (it'll be in the next nightly build) workable? Or should we add extra code to make it happen without the Enter key being needed? And if so, how should we handle multi-selection when multiple fields are selected?

**Comment by tonypdmtr** [comment]
Indeed, now ENTER is needed all the time whether for **both** keyboard and mouse.  (This feels awkward to me.  It's certainly worse for mouse users as they now have to use both mouse and keyboard.)

I'm not sure of the previous mouse behavior but didn't it update the edit box with each mouse click?  If so, then perhaps the mouse click event could be 'manually' called whenever the grid cell is changed by keyboard, no?  (I suppose there is some way to detect that, I don't know QT.)

**Comment by mgrojo** [comment]
I've made the same signal/slot connection as for the Browse Data table. Both tables behave now the same. Don't know if there could be any unwanted side effect but I haven't found any. @sky5walk Please, test with tomorrow's build and report any nuisance.

**Comment by sky5walk** [comment]
181229 nightly works 😄

**Comment by mgrojo** [comment]
Thanks. I think this can be closed, then.
