### ISSUE TITLE
Memory leak in import CSV

### ISSUE THREAD

**Issue by gelldur** [sqlitebrowser/sqlitebrowser#792]
### Details for the issue

When I import large CSV tables memory leak occurs. After import memory should be free. Eg. Now sqlitebrowser is using 10 GB RAM
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [ ] Windows
- [x] Linux: ( _distro:_ Manjaro (Arch) )
- [ ] Mac OS
- [ ] Other: ___
#### I'm using DB4S version:
- [x] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
> large CSV tables.  

Out of interest, how large is large?  How many fields per line, and how many records?  Is this after one import, or after a series of imports?

**Comment by gelldur** [comment]
> 1 GB csv files. It occurs in single import. Aftert import success RAM is still in use. (10 GB+)

One of my CSV:
20 376 731 rows
17 columns

**Comment by justinclift** [comment]
Well, that definitely sounds like a bug. :smile:

Guess we'll need to come to grips with Valgrind & similar soon. :wink:

**Comment by revolter** [comment]
It looks like the memory leak is happening [on this line][1], but I can't figure out what's the problem. Maybe @MKleusberg or @innermous have some ideas?

  [1]: https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/DbStructureModel.cpp#L155

**Comment by justinclift** [comment]
Hmm, looking at it quickly:

    QTreeWidgetItem* itemTables = new QTreeWidgetItem(itemAll);

If that method is called multiple times, then maybe "itemTables" is given a brand new QTreeWidgetItem() on each call, and nothing frees the memory of the old QTreeWidgetItem() from the previous call?

**Comment by gelldur** [comment]
Also i can add that this bug occurs when all columns are as 'TEXT'.
When i first create table leak is much less. By create table i mean create it with better data formats for columns

**Comment by justinclift** [comment]
Thanks, that's helpful. :smile:

**Comment by MKleusberg** [comment]
I've fixed all the memory leaks that Valgrind would tell me about after opening a database, importing some CSV into it, and then closing the application. Here's the commit 7b86b17788cadb7ec08a7bed39aa214dcc42b526. This also fixes the memory leak that Iulian observed.
However, none of these are related to CSV. The one mentioned by Iulian was the only one that was happening during the actual import. But it happened only once - after creating the new tablee - and didn't leak enough memory to be noticeable at first. Other than these, there are no memory leaks reported by Valgrind (well, except for a smaller one in QHexEdit). So this might just be caused the behaviour of the memory manager of the operating system but I'm not sure.

Either way, the CSV import uses *way* too much memory. That's where I'd start at least. Maybe don't use Qt objects in there. And maybe we shouldn't read the entire file into memory first; for large files it might be better to INSERT the rows every now and then and free the memory.

**Comment by prutz1311** [comment]
The memory leak still occurs, for example, when I import a 200M csv file, sqlitebrowser uses something like 2.4 Gb of RAM (60%) and does not release it after the import. Maybe that's due to the way `QTextStream` and `QFile` work. In contrast `.import` command of the command-line tool `sqlite3` uses only about 0.1% of my 4Gb RAM (`ps aux` output). Would it be a good idea to try to include their implementation of import?

**Comment by innermous** [comment]
@prutz1311 could you provide data set, please?

**Comment by prutz1311** [comment]
Something like that https://drive.google.com/drive/folders/0B0ARB4SyceKZcUV0MUFMMUJiajg

**Comment by MKleusberg** [comment]
I've just pushed a commit which should improve this a lot. I still don't see any memory leak, so I think it is just that we use a lot of memory during the import and actually free it afterwards but the operating system doesn't take it back until it needs to (or some similar explanation). But either way, we're now using a lot less memory during import which means there is a lot less memory to be reclaimed or lost 😄 

@gelldur Do you still have that CSV file somewhere and want to try it with tomorrow's nightly build (or any later one)? It shouldn't take 10GB anymore and it should be a bit faster too :smile:

Same for you, @prutz1311, memory consumption should be a lot closer to the one of the sqlite3 utility. I've also had a quick look at their code and it looked like it didn't support as many options as we do (encoding, quote char, separator char, ...). So unfortunately we can't just copy it, and it's probably always going to be a bit faster than our code.

**Comment by gelldur** [comment]
Nope sorry I don't have such file :( (old project with sensitive data) but I'm happy that there is improvement :)

**Comment by innermous** [comment]
Still doesn't free all the memory allocated.

**Comment by MKleusberg** [comment]
@gelldur No problem at all 😄 I'll just close this issue then because I believe the original issue is fixed now. If you should ever stumble upon a CSV file of a similar size and you feel like it's not working using the latest build, you're of course welcome to reopen this issue or just open a new one :smile:

@innermous You were right. There was another memory leak, not directly in the CSV code but in a code branch that would be called whenever you import data into a new table. It's fixed by [this commit](28446a4f0cba71122e37788e46171c2fd3fab448). Now there shouldn't be any memory leaks left. At least that's what Valgrind and Coverity say.
