### ISSUE TITLE
Cannot modify values in a table having a field which other table's foreign key refers to

### ISSUE THREAD

**Issue by prutz1311** [sqlitebrowser/sqlitebrowser#901]
### Details for the issue

When trying to reproduce #463, I found that it is impossible to change the value of primary key of table A after I have created a row if pragma `foreign_keys` is on:
![image](https://cloud.githubusercontent.com/assets/6525383/21108323/dd91f470-c0a5-11e6-89de-731193652384.png)
```sql
CREATE TABLE "A" ( `ID` INTEGER, `txt` TEXT )
CREATE TABLE `B` ( `AID` INTEGER, `txt` TEXT, FOREIGN KEY(`AID`) REFERENCES A(ID) )
```
Seems like [`sqlite3_prepare_v2`](https://github.com/sqlitebrowser/sqlitebrowser/blob/e6a8f882550177bcbf2a2a8ada7d575fae4abad6/src/sqlitedb.cpp#L922) does not work with `foreign_keys` pragma enabled.
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro: Xubuntu 14.04.5 LTS trusty)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [x] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ouch, that's not good.  Any interest in fixing it? 😁

**Comment by prutz1311** [comment]
Updating uses SQL `?` substitution, so it has to call  `sqlite3_prepare_v2` and then `sqlite3_bind_blob` or `sqlite3_bind_text` to actually fill in the value. The possible solution might be to disable foreign keys before updating but that will make foreign keys useless.

**Comment by justinclift** [comment]
Hmmm, yeah I'm not sure of a good approach here either. 😦

**Comment by prutz1311** [comment]
Maybe we should report to sqlite developers about `sqlite3_prepare_v2` failure? Because it seems like there is no other thing which we can rely on to enable foreign keys support.

**Comment by MKleusberg** [comment]
Interesting... To me this looks like an SQLite bug. At least I don't think we have any chance to fix this from our side. Of course, we could not use ```sqlite3_prepare_v2``` but that would cause trouble with BLOBs; or we could disable foreign key support but that would cause trouble with... well... foreign keys obviously.

I've tried to reduce this problem to a minimal example:
1) Create database
```
$ sqlite3 issue901.db
SQLite version 3.15.2 2016-11-28 19:13:37
Enter ".help" for usage hints.
sqlite> CREATE TABLE `a`(`id` integer);
sqlite> CREATE TABLE `b`(`aid` integer, FOREIGN KEY(`aid`) REFERENCES `a`(`id`));
sqlite> INSERT INTO `a` VALUES(1);
sqlite> .quit
```

2) Minimal C program (issue901.c)
```c
#include <sqlite3.h>
#include <stdio.h>

#define NOTWORKING

int main()
{
	sqlite3* db;
	if(sqlite3_open_v2("issue901.db", &db, SQLITE_OPEN_READWRITE, NULL) != SQLITE_OK)
	{
		printf("sqlite3_open_v2 failed!\n");
		return 1;
	}

#ifdef NOTWORKING
	if(sqlite3_exec(db, "PRAGMA foreign_keys=\"1\"", NULL, NULL, NULL) != SQLITE_OK)
	{
		printf("Enabling foreign keys failed!\n");
		return 1;
	}
#endif

	sqlite3_stmt* stmt;
	if(sqlite3_prepare_v2(db, "UPDATE `a` SET `id`=7 WHERE `id`=1;", -1, &stmt, 0) != SQLITE_OK)
	{
		printf("sqlite3_prepare_v2 failed!\n%s\n", sqlite3_errmsg(db));
		return 1;
	}

	sqlite3_close(db);
	return 0;
}
```

3) Build and run
```
$ gcc -lsqlite3 -o issue901 issue901.c
$ ./issue901
sqlite3_prepare_v2 failed!
foreign key mismatch - "b" referencing "a"
```

The example demonstrates that the problem is caused by ```sqlite3_prepare_v2```. It also shows that it depends on foreign keys being enabled.

If someone has the time, feel free to forward this to the SQLite mailing list. Maybe they can point us into the right direction :)

**Comment by prutz1311** [comment]
SQLite developers say:

"The parent column must be UNIQUE.  I suggest changing the first table
definition to:

   ```CREATE TABLE "a"("id" INTEGER PRIMARY KEY);```

Note also that `...` identifier quoting is a deprecated MySQL-ism.
The perferred way to quote identifiers in SQL is with double-quotes:
"..."."

I also didn't google enough and didn't notice this https://www.sqlite.org/foreignkeys.html#fk_indexes.
The original issue #463 also gets reproduced without errors. So this issue can probably be closed.

**Comment by MKleusberg** [comment]
Thanks @prutz1311 for looking into this! :+1: I've just asked the original reporter from issue #463 to test it again using your information. If it works for them I think we can close both issues :)

**Comment by justinclift** [comment]
@MKleusberg As #463 is fixed, we're ok to close this now aren't we?

**Comment by MKleusberg** [comment]
@justinclift Yeah. I can still reproduce the problem but it's just how SQLite works. So no reason to keep this open :smiley:
